language: node_js
node_js: 
  - 8
script: 
  - "npm run build"
cache: 
  directories: 
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  repo: MarvinXu/marvinxu.github.io
  local_dir: public
  on:
    branch: master